<#
.SYNOPSIS
    OmniRoute launcher (Variant 3): official Codex with main reasoning
    rerouted to OmniRoute, via a narrowly-isolated CODEX_HOME.

.DESCRIPTION
    Codex OmniRoute is intentionally a thin mode switch on top of the
    unmodified Microsoft Store Codex app. The architecture has three
    moving parts:

      1. A local Node bridge (codex-openai-omniroute-bridge.mjs) that:
           - reroutes /v1/responses and /v1/chat/completions to OmniRoute;
           - forwards everything else (compact, dictation, models cache,
             account stuff) to the official upstream unchanged.

      2. An isolated CODEX_HOME (".codex-omniroute-home" next to this
         launcher) seeded from the user's real ~/.codex:
             auth.json         <- copied from user's real auth.json
                                  (keeps the user signed in with the SAME
                                  ChatGPT account; fast mode + ChatGPT
                                  credits keep working).
             models_cache.json <- copied if present, so the bridge's
                                  /v1/models route has data.
             config.toml       <- regenerated by this launcher; selects
                                   model_provider = "omniroute_bridge"
                                   and imports selected tooling sections.
         state_5.sqlite*, logs_2.sqlite*, sessions/, session_index.jsonl,
         and .codex-global-state.json are preserved in place so OmniRoute
         chat history survives restarts. The user's real ~/.codex history
         is NEVER touched.

      3. The launcher exports CODEX_HOME=<isolated path> into its own
         process environment for the bridge child process, then writes
         the same value to the user's Windows environment before AppX
         activation. AppX activation and late Desktop helpers are
         brokered by Windows and do not inherit arbitrary process-scope
         variables from this PowerShell process. A hidden restore watcher
         restores the previous user value after the activated Codex
         Desktop/AppX process tree has exited. During the same lease, it
         also prepends a generated quiet taskkill.exe shim to user-scope
         PATH so Codex app-server MCP cleanup cannot pollute JSON-RPC
         stdout with taskkill success text; the same watcher restores the
         previous PATH. USERPROFILE / APPDATA / HOME / LOCALAPPDATA /
         TEMP / TMP are NOT overridden -- so apply_patch, MCP, git, rg,
         file dialogs, ~/.gitconfig, ~/.ssh continue to resolve against
         the user's real Windows profile.

    The launcher never writes OmniRoute managed blocks or auth sentinels
    into the user's real %USERPROFILE%\.codex directory. If the real
    config.toml is detected as the known mojibake/path-corruption case,
    it is backed up and repaired from the known-good pre-normalize backup.
    As a result there is no restore-of-managed-config to do on the way
    back out -- the official launcher just stops the bridge and helpers.

    For users upgrading from earlier versions (PR #3 + earlier) we DO
    sweep up any legacy artifacts left in the user's real ~/.codex by
    those launchers: a leftover managed block in config.toml, a
    sentinel auth.json, and the *.codex-omniroute-backup files. The
    sweep is a best-effort one-shot reverse-of-PR-#3 so the user does
    not have to manually clean their profile when switching to this
    version.

    Codex.exe itself is launched through the AppX activation broker
    (IApplicationActivationManager), exactly the way Start-Menu and
    Start-Codex-Official.ps1 launch it. This preserves Microsoft Store
    package identity for Codex AND for every child shell it spawns, so
    codex-command-runner.exe, rg.exe, and other bundled CLI tools stay
    in the AppX-launched context. Because Store-provided apply_patch.bat
    can resolve to an inaccessible WindowsApps target in child shells, a
    tiny local watcher rewrites that wrapper to the local Codex CLI helper.

.PARAMETER NoCodex
    Start the bridge and seed the isolated CODEX_HOME, but do NOT launch
    the Codex GUI. Used by verify-codex-omniroute.ps1.

.PARAMETER Restore
    Stop the managed bridge and wipe the isolated CODEX_HOME directory.
    Also reverses any legacy PR-#3 artifacts in the user's real ~/.codex
    (managed block in config.toml, sentinel auth.json, backup files).
    Does not launch Codex.

.PARAMETER DryRun
    Print what would be done (port choice, isolated CODEX_HOME path)
    without starting the bridge, seeding the isolated dir, or
    launching Codex.

.PARAMETER BridgePort
    Preferred bridge port. The launcher will search nearby ports if this
    one is busy. Default 20333.

.PARAMETER ProviderJson
    Path to omniroute-provider.json. Defaults to ./omniroute-provider.json
    relative to the script. May also be configured via env
    OMNIROUTE_PROVIDER_JSON, OMNIROUTE_BASE_URL+OMNIROUTE_API_KEY, or via
    ~/.config/opencode/auth.json (see codex-openai-omniroute-bridge.mjs).

.PARAMETER OpenProject
    Optional path to a project. If set, Codex is launched with
    `--open-project <path>`. Default: do not pre-open a project (Codex
    shows its normal project picker over the user's real filesystem).

.PARAMETER NoFreeformApplyPatch
    Do not emit `apply_patch_freeform = true` in the [features] sections of the
    isolated config.toml. Default: emit it as an additional safety net;
    literal apply_patch is handled by the local rewriter/helper path.

.PARAMETER UserCodexHomeRestoreTimeoutSec
    Maximum number of seconds the hidden restore watcher may leave the
    user-scope CODEX_HOME pointing at the isolated home. Default: 0,
    which means "until the activated Codex Desktop/AppX process tree has
    exited"; non-zero values are a safety ceiling for troubleshooting.

.NOTES
    - Never modifies the Microsoft Store Codex package.
    - Never writes OmniRoute managed blocks into %USERPROFILE%\.codex; a
      corrupted real config is backed up before deterministic repair.
    - The isolated CODEX_HOME is reseeded in place on every launch:
      auth.json + models_cache.json are refreshed from the user's real
      profile, managed config/tooling files are rewritten, and Codex
      history/state files are preserved.
    - On -Restore, the isolated CODEX_HOME is removed and any legacy
      PR-#3 artifacts in the user's real ~/.codex are reversed. Any
      stale user-scope CODEX_HOME or taskkill-shim PATH prefix left by an
      interrupted OmniRoute launch is also cleared if it points at this
      isolated home.
#>

[CmdletBinding()]
param(
    [switch]$NoCodex,
    [switch]$Restore,
    [switch]$DryRun,
    [int]$BridgePort = 20333,
    [string]$ProviderJson = './omniroute-provider.json',
    [string]$OpenProject = '',
    [switch]$NoFreeformApplyPatch,
    [switch]$NoApplyPatchRewriter,
    [switch]$NoMcpProbe,
    [switch]$NoConfigRepair,
    [int]$UserCodexHomeRestoreTimeoutSec = 0
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

# ----------------------------------------------------------------------------
# Constants
# ----------------------------------------------------------------------------

# Legacy markers from PR #2 / PR #3 (managed-block-in-real-config-toml and
# managed-auth-sentinel). Kept here ONLY so the cleanup pass on launch /
# -Restore can recognize and reverse them. The current architecture does
# NOT write either of these into the user's real ~/.codex.
$LegacyManagedBlockBegin       = '# >>> codex-omniroute-managed (auto-generated; do not edit by hand)'
$LegacyManagedBlockEnd         = '# <<< codex-omniroute-managed'
$LegacyManagedAuthSentinelKey  = 'sk-omniroute-managed'

# Name of the isolated CODEX_HOME directory under the script root.
$IsolatedHomeDirName = '.codex-omniroute-home'
$ConfigOverlayFileName = 'codex-omniroute-config-overlay.toml'
$KnownGoodConfigBackupFileName = 'config.before-mcp-normalize.20260501T043553.toml'
$ApplyPatchRewriterPidFileName = 'apply_patch_rewriter.pid'
$ApplyPatchRewriterLogFileName = 'apply_patch_rewriter.log'
$OmniRouteCatalogScriptRelPath = 'tools\omniroute-catalog.mjs'
$OmniRouteCatalogBundleFileName = 'default-mcp-catalog.json'
$OmniRouteCatalogCacheFileName = '.codex-omniroute-catalog-cache.json'
$OmniRouteCatalogTomlFileName = '.codex-omniroute-catalog.toml'

# ----------------------------------------------------------------------------
# Host platform detection
#
# Touching `$IsWindows` directly is unsafe: Windows PowerShell 5.x does not
# define it, and under `Set-StrictMode -Version Latest` an undefined variable
# is a hard error. This helper resolves the host platform without ever
# evaluating `$IsWindows` in a way that the strict-mode parser would reject.
# It returns $true on:
#   - Windows PowerShell 5.x (PSEdition = 'Desktop' is Windows-only by design)
#   - PowerShell 7+ on Windows ($IsWindows = $true, fetched via Get-Variable)
#   - any other host where %OS% is reported as Windows_NT
# and $false on PowerShell 7+ on Linux/macOS (used by CI / verification).
# ----------------------------------------------------------------------------

function Test-WindowsHost {
    if ($PSVersionTable.PSEdition -eq 'Desktop') { return $true }
    $winVar = Get-Variable -Name 'IsWindows' -ErrorAction SilentlyContinue
    if ($winVar) { return [bool]$winVar.Value }
    if ($env:OS -eq 'Windows_NT') { return $true }
    return $false
}

function Test-SameEnvironmentValue {
    param(
        [AllowNull()][string]$Left,
        [AllowNull()][string]$Right
    )
    return [string]::Equals($Left, $Right, [System.StringComparison]::OrdinalIgnoreCase)
}

function Publish-UserEnvironmentChange {
    if (-not (Test-WindowsHost)) { return }

    if (-not ('CodexOmniRouteEnvBroadcaster' -as [type])) {
        Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

public static class CodexOmniRouteEnvBroadcaster {
    private static readonly IntPtr HWND_BROADCAST = new IntPtr(0xffff);
    private const uint WM_SETTINGCHANGE = 0x001A;
    private const uint SMTO_ABORTIFHUNG = 0x0002;

    [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
    private static extern IntPtr SendMessageTimeout(
        IntPtr hWnd,
        uint Msg,
        UIntPtr wParam,
        string lParam,
        uint fuFlags,
        uint uTimeout,
        out UIntPtr lpdwResult);

    public static void BroadcastEnvironmentChange() {
        UIntPtr result;
        SendMessageTimeout(
            HWND_BROADCAST,
            WM_SETTINGCHANGE,
            UIntPtr.Zero,
            "Environment",
            SMTO_ABORTIFHUNG,
            5000,
            out result);
    }
}
'@
    }

    try { [CodexOmniRouteEnvBroadcaster]::BroadcastEnvironmentChange() } catch {}
}

function Set-UserCodexHomeOverride {
    param([AllowNull()][string]$Value)
    if (-not (Test-WindowsHost)) { return }

    [System.Environment]::SetEnvironmentVariable('CODEX_HOME', $Value, 'User')
    Publish-UserEnvironmentChange
}

function Set-UserPathOverride {
    param([AllowNull()][string]$Value)
    if (-not (Test-WindowsHost)) { return }

    [System.Environment]::SetEnvironmentVariable('PATH', $Value, 'User')
    Publish-UserEnvironmentChange
}

function Join-PathPrefix {
    param(
        [AllowNull()][string]$PathValue,
        [Parameter(Mandatory = $true)][string]$Prefix
    )

    if ([string]::IsNullOrWhiteSpace($PathValue)) { return $Prefix }
    $parts = @($PathValue -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
    $filtered = @($parts | Where-Object { -not (Test-SameEnvironmentValue $_ $Prefix) })
    return (@($Prefix) + $filtered) -join ';'
}

function Clear-StaleTaskkillShimPathOverride {
    param([Parameter(Mandatory = $true)][string]$ShimDir)
    if (-not (Test-WindowsHost)) { return }
    if ([string]::IsNullOrWhiteSpace($ShimDir)) { return }

    $currentUserPath = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
    if ([string]::IsNullOrWhiteSpace($currentUserPath)) { return }
    $parts = @($currentUserPath -split ';')
    if ($parts.Count -eq 0) { return }
    if (-not (Test-SameEnvironmentValue $parts[0] $ShimDir)) { return }
    $rest = @($parts | Select-Object -Skip 1)
    $newPath = ($rest -join ';')
    if ([string]::IsNullOrWhiteSpace($newPath)) { $newPath = $null }
    Set-UserPathOverride -Value $newPath
    Write-Host "[omniroute] cleared stale user-scope PATH taskkill shim prefix"
}

function Clear-StaleUserCodexHomeOverride {
    param([Parameter(Mandatory = $true)][string]$IsolatedHome)
    if (-not (Test-WindowsHost)) { return }

    $currentUserCodexHome = [System.Environment]::GetEnvironmentVariable('CODEX_HOME', 'User')
    if (Test-SameEnvironmentValue $currentUserCodexHome $IsolatedHome) {
        Set-UserCodexHomeOverride -Value $null
        Write-Host "[omniroute] cleared stale user-scope CODEX_HOME override"
    }
}

function Resolve-CSharpCompiler {
    $candidates = @()
    if ($env:WINDIR) {
        $candidates += (Join-Path $env:WINDIR 'Microsoft.NET\Framework64\v4.0.30319\csc.exe')
        $candidates += (Join-Path $env:WINDIR 'Microsoft.NET\Framework\v4.0.30319\csc.exe')
    }
    $cmd = Get-Command csc.exe -ErrorAction SilentlyContinue
    if ($cmd) { $candidates += $cmd.Source }
    foreach ($candidate in $candidates) {
        if ($candidate -and (Test-Path -LiteralPath $candidate)) { return $candidate }
    }
    return $null
}

function Ensure-TaskkillQuietShim {
    param(
        [Parameter(Mandatory = $true)][string]$IsolatedHome,
        [Parameter(Mandatory = $true)][string]$ScriptRoot
    )

    if (-not (Test-WindowsHost)) { return $null }
    $source = Join-Path $ScriptRoot 'tools\taskkill-quiet-shim.cs'
    if (-not (Test-Path -LiteralPath $source)) {
        Write-Warning "[omniroute] taskkill quiet shim source missing at $source"
        return $null
    }

    $shimDir = Join-Path $IsolatedHome 'bin'
    $shimExe = Join-Path $shimDir 'taskkill.exe'
    New-Item -ItemType Directory -Path $shimDir -Force | Out-Null

    $needsCompile = -not (Test-Path -LiteralPath $shimExe)
    if (-not $needsCompile) {
        $srcItem = Get-Item -LiteralPath $source -ErrorAction SilentlyContinue
        $exeItem = Get-Item -LiteralPath $shimExe -ErrorAction SilentlyContinue
        if ($srcItem -and $exeItem -and $exeItem.LastWriteTimeUtc -lt $srcItem.LastWriteTimeUtc) {
            $needsCompile = $true
        }
    }
    if (-not $needsCompile) { return $shimDir }

    $csc = Resolve-CSharpCompiler
    if (-not $csc) {
        Write-Warning "[omniroute] csc.exe not found; cannot build taskkill quiet shim. MCP app-server stdio may still be polluted by taskkill output."
        return $null
    }

    $raw = & $csc /nologo /target:exe /out:$shimExe $source 2>&1
    $exit = $LASTEXITCODE
    if ($exit -ne 0 -or -not (Test-Path -LiteralPath $shimExe)) {
        $detail = (($raw | Out-String).Trim())
        Write-Warning "[omniroute] failed to build taskkill quiet shim (exit=$exit): $detail"
        return $null
    }
    Write-Host "[omniroute] built taskkill quiet shim at $shimExe"
    return $shimDir
}

function ConvertTo-PowerShellLiteral {
    param([AllowNull()][string]$Value)
    if ($null -eq $Value) { return '$null' }
    return "'" + $Value.Replace("'", "''") + "'"
}

function Start-UserCodexHomeRestoreWatcher {
    param(
        [Parameter(Mandatory = $true)][string]$IsolatedHome,
        [AllowNull()][string]$PreviousUserCodexHome,
        [AllowNull()][string]$TaskkillShimDir,
        [AllowNull()][string]$PreviousUserPath,
        [AllowNull()][string]$ExpectedUserPath,
        [int]$TimeoutSec = 0,
        [Parameter(Mandatory = $true)][datetime]$ActivationStartedAtUtc,
        [uint32]$ActivatedPid = 0,
        [AllowNull()][string]$PackageInstallLocation
    )
    if (-not (Test-WindowsHost)) { return $false }
    if ($TimeoutSec -lt 0) { $TimeoutSec = 0 }

    $hadPrevious = ($null -ne $PreviousUserCodexHome)
    $previousLiteral = ConvertTo-PowerShellLiteral -Value $PreviousUserCodexHome
    $isolatedLiteral = ConvertTo-PowerShellLiteral -Value $IsolatedHome
    $taskkillShimLiteral = ConvertTo-PowerShellLiteral -Value $TaskkillShimDir
    $previousPathLiteral = ConvertTo-PowerShellLiteral -Value $PreviousUserPath
    $expectedPathLiteral = ConvertTo-PowerShellLiteral -Value $ExpectedUserPath
    $activationLiteral = ConvertTo-PowerShellLiteral -Value ($ActivationStartedAtUtc.ToString('o'))
    $packageRootLiteral = ConvertTo-PowerShellLiteral -Value $PackageInstallLocation
    $hadPreviousLiteral = if ($hadPrevious) { '$true' } else { '$false' }
    $hadPreviousPathLiteral = if ($null -ne $PreviousUserPath) { '$true' } else { '$false' }

    $watcher = @"
`$ErrorActionPreference = 'SilentlyContinue'
`$isolatedHome = $isolatedLiteral
`$previousUserCodexHome = $previousLiteral
`$hadPreviousUserCodexHome = $hadPreviousLiteral
`$taskkillShimDir = $taskkillShimLiteral
`$previousUserPath = $previousPathLiteral
`$expectedUserPath = $expectedPathLiteral
`$hadPreviousUserPath = $hadPreviousPathLiteral
`$activationStartedAtUtc = [datetime]$activationLiteral
`$timeoutSec = $TimeoutSec
`$activatedPid = [uint32]$ActivatedPid
`$packageRoot = $packageRootLiteral
`$bootstrapGraceSec = 45
`$shutdownQuietSec = 45

function Test-SameEnvironmentValue {
    param([AllowNull()][string]`$Left, [AllowNull()][string]`$Right)
    return [string]::Equals(`$Left, `$Right, [System.StringComparison]::OrdinalIgnoreCase)
}

function Test-PathUnderRoot {
    param([AllowNull()][string]`$Path, [AllowNull()][string]`$Root)
    if ([string]::IsNullOrWhiteSpace(`$Path) -or [string]::IsNullOrWhiteSpace(`$Root)) { return `$false }
    `$normalizedRoot = `$Root.TrimEnd('\', '/') + '\'
    return `$Path.StartsWith(`$normalizedRoot, [System.StringComparison]::OrdinalIgnoreCase)
}

function Publish-UserEnvironmentChange {
    try {
        Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

public static class CodexOmniRouteRestoreWatcherEnvBroadcaster {
    private static readonly IntPtr HWND_BROADCAST = new IntPtr(0xffff);
    private const uint WM_SETTINGCHANGE = 0x001A;
    private const uint SMTO_ABORTIFHUNG = 0x0002;

    [DllImport("user32.dll", CharSet = CharSet.Auto, SetLastError = true)]
    private static extern IntPtr SendMessageTimeout(
        IntPtr hWnd,
        uint Msg,
        UIntPtr wParam,
        string lParam,
        uint fuFlags,
        uint uTimeout,
        out UIntPtr lpdwResult);

    public static void BroadcastEnvironmentChange() {
        UIntPtr result;
        SendMessageTimeout(
            HWND_BROADCAST,
            WM_SETTINGCHANGE,
            UIntPtr.Zero,
            "Environment",
            SMTO_ABORTIFHUNG,
            5000,
            out result);
    }
}
'@ | Out-Null
        [CodexOmniRouteRestoreWatcherEnvBroadcaster]::BroadcastEnvironmentChange()
    } catch {}
}

function Restore-UserCodexHome {
    `$current = [System.Environment]::GetEnvironmentVariable('CODEX_HOME', 'User')
    if (-not (Test-SameEnvironmentValue `$current `$isolatedHome)) { return }
    if (`$hadPreviousUserCodexHome) {
        [System.Environment]::SetEnvironmentVariable('CODEX_HOME', `$previousUserCodexHome, 'User')
    } else {
        [System.Environment]::SetEnvironmentVariable('CODEX_HOME', `$null, 'User')
    }
    Publish-UserEnvironmentChange
}

function Restore-UserPath {
    if ([string]::IsNullOrWhiteSpace(`$taskkillShimDir)) { return }
    `$current = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
    if ([string]::Equals(`$current, `$expectedUserPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        if (`$hadPreviousUserPath) {
            [System.Environment]::SetEnvironmentVariable('PATH', `$previousUserPath, 'User')
        } else {
            [System.Environment]::SetEnvironmentVariable('PATH', `$null, 'User')
        }
        Publish-UserEnvironmentChange
        return
    }
    if ([string]::IsNullOrWhiteSpace(`$current)) { return }
    `$parts = @(`$current -split ';')
    if (`$parts.Count -eq 0) { return }
    if (-not (Test-SameEnvironmentValue `$parts[0] `$taskkillShimDir)) { return }
    `$rest = @(`$parts | Select-Object -Skip 1)
    `$newPath = (`$rest -join ';')
    if ([string]::IsNullOrWhiteSpace(`$newPath)) { `$newPath = `$null }
    [System.Environment]::SetEnvironmentVariable('PATH', `$newPath, 'User')
    Publish-UserEnvironmentChange
}

function Convert-ProcessCreationTimeUtc {
    param([AllowNull()]`$Value)
    if (`$null -eq `$Value) { return [datetime]::MinValue }
    try {
        if (`$Value -is [datetime]) { return `$Value.ToUniversalTime() }
        return ([System.Management.ManagementDateTimeConverter]::ToDateTime([string]`$Value)).ToUniversalTime()
    } catch {
        return [datetime]::MinValue
    }
}

function Get-CodexProcessRows {
    `$rows = @()
    try { `$rows = @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue) } catch { }
    if (`$rows.Count -eq 0) {
        try { `$rows = @(Get-WmiObject Win32_Process -ErrorAction SilentlyContinue) } catch { }
    }
    if (`$rows.Count -gt 0) { return `$rows }

    `$fallback = New-Object System.Collections.Generic.List[object]
    foreach (`$proc in @(Get-Process -ErrorAction SilentlyContinue)) {
        `$path = `$null
        `$start = [datetime]::MinValue
        try { `$path = `$proc.Path } catch { }
        try { `$start = `$proc.StartTime.ToUniversalTime() } catch { }
        `$fallback.Add([pscustomobject]@{
            ProcessId       = `$proc.Id
            ParentProcessId = 0
            Name            = (`$proc.ProcessName + '.exe')
            ExecutablePath  = `$path
            CreationDate    = `$start
        })
    }
    return @(`$fallback.ToArray())
}

function Get-TrackedCodexProcessCount {
    `$threshold = `$activationStartedAtUtc.AddSeconds(-10)
    `$rows = @(Get-CodexProcessRows)
    if (`$rows.Count -eq 0) { return 0 }

    `$tracked = New-Object 'System.Collections.Generic.HashSet[int]'
    foreach (`$row in `$rows) {
        `$pid = 0
        try { `$pid = [int]`$row.ProcessId } catch { continue }
        `$name = [string]`$row.Name
        `$path = [string]`$row.ExecutablePath
        `$createdUtc = Convert-ProcessCreationTimeUtc `$row.CreationDate
        `$isActivated = (`$activatedPid -gt 0 -and `$pid -eq [int]`$activatedPid)
        `$isPackageProcess = Test-PathUnderRoot -Path `$path -Root `$packageRoot
        `$isCodexNamed = (`$name -match '(?i)^codex.*\.exe\z')
        if (`$isActivated -or `$isPackageProcess -or (`$isCodexNamed -and `$createdUtc -ge `$threshold)) {
            [void]`$tracked.Add(`$pid)
        }
    }

    `$changed = `$true
    while (`$changed) {
        `$changed = `$false
        foreach (`$row in `$rows) {
            `$pid = 0
            `$ppid = 0
            try { `$pid = [int]`$row.ProcessId; `$ppid = [int]`$row.ParentProcessId } catch { continue }
            if (`$tracked.Contains(`$pid)) { continue }
            if (`$tracked.Contains(`$ppid)) {
                [void]`$tracked.Add(`$pid)
                `$changed = `$true
            }
        }
    }

    return `$tracked.Count
}

function Restore-And-Exit {
    Restore-UserCodexHome
    Restore-UserPath
    exit 0
}

`$sawTrackedProcess = `$false
`$emptySinceUtc = `$null
`$bootstrapDeadline = `$activationStartedAtUtc.AddSeconds(`$bootstrapGraceSec)
`$hardDeadline = [datetime]::MaxValue
if (`$timeoutSec -gt 0) {
    `$hardDeadline = (Get-Date).ToUniversalTime().AddSeconds(`$timeoutSec)
}

while ((Get-Date).ToUniversalTime() -lt `$hardDeadline) {
    `$current = [System.Environment]::GetEnvironmentVariable('CODEX_HOME', 'User')
    if (-not (Test-SameEnvironmentValue `$current `$isolatedHome)) {
        Restore-UserPath
        exit 0
    }

    `$trackedCount = Get-TrackedCodexProcessCount
    `$now = (Get-Date).ToUniversalTime()
    if (`$trackedCount -gt 0) {
        `$sawTrackedProcess = `$true
        `$emptySinceUtc = `$null
    } elseif (-not `$sawTrackedProcess) {
        if (`$now -ge `$bootstrapDeadline) { Restore-And-Exit }
    } else {
        if (`$null -eq `$emptySinceUtc) { `$emptySinceUtc = `$now }
        if (`$now -ge `$emptySinceUtc.AddSeconds(`$shutdownQuietSec)) { Restore-And-Exit }
    }

    Start-Sleep -Seconds 2
}
Restore-And-Exit
"@

    try {
        $encoded = [Convert]::ToBase64String([System.Text.Encoding]::Unicode.GetBytes($watcher))
        $cmd = Get-Command pwsh -ErrorAction SilentlyContinue
        if (-not $cmd) { $cmd = Get-Command powershell -ErrorAction SilentlyContinue }
        if (-not $cmd) { return $false }
        $args = @('-NoLogo', '-NoProfile', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', $encoded)
        $startArgs = @{
            FilePath     = $cmd.Source
            ArgumentList = $args
            PassThru     = $true
        }
        if (Test-WindowsHost) {
            $startArgs['WindowStyle'] = 'Hidden'
        }
        $proc = Start-Process @startArgs
        if ($proc) {
            $leaseText = if ($TimeoutSec -gt 0) { "timeout=${TimeoutSec}s" } else { "lifecycle" }
            Write-Host ("[omniroute] user-scope CODEX_HOME/PATH lifecycle watcher running (pid={0}, {1})" -f $proc.Id, $leaseText)
            return $true
        }
    } catch { }
    return $false
}

function Restore-UserCodexHomeOverrideNow {
    param(
        [Parameter(Mandatory = $true)][string]$IsolatedHome,
        [AllowNull()][string]$PreviousUserCodexHome,
        [AllowNull()][string]$TaskkillShimDir,
        [AllowNull()][string]$PreviousUserPath,
        [AllowNull()][string]$ExpectedUserPath
    )
    if (-not (Test-WindowsHost)) { return }
    $currentUserCodexHome = [System.Environment]::GetEnvironmentVariable('CODEX_HOME', 'User')
    if (Test-SameEnvironmentValue $currentUserCodexHome $IsolatedHome) {
        Set-UserCodexHomeOverride -Value $PreviousUserCodexHome
        if ($null -eq $PreviousUserCodexHome) {
            Write-Host "[omniroute] restored user-scope CODEX_HOME (cleared temporary override)"
        } else {
            Write-Host "[omniroute] restored previous user-scope CODEX_HOME"
        }
    } else {
        Write-Warning "[omniroute] user-scope CODEX_HOME changed during activation; leaving current value untouched."
    }

    if (-not [string]::IsNullOrWhiteSpace($TaskkillShimDir)) {
        $currentUserPath = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
        if ([string]::Equals($currentUserPath, $ExpectedUserPath, [System.StringComparison]::OrdinalIgnoreCase)) {
            Set-UserPathOverride -Value $PreviousUserPath
            Write-Host "[omniroute] restored user-scope PATH taskkill shim prefix"
        } elseif (-not [string]::IsNullOrWhiteSpace($currentUserPath)) {
            $parts = @($currentUserPath -split ';')
            if ($parts.Count -gt 0 -and (Test-SameEnvironmentValue $parts[0] $TaskkillShimDir)) {
                $rest = @($parts | Select-Object -Skip 1)
                $newPath = ($rest -join ';')
                if ([string]::IsNullOrWhiteSpace($newPath)) { $newPath = $null }
                Set-UserPathOverride -Value $newPath
                Write-Host "[omniroute] removed user-scope PATH taskkill shim prefix"
            } else {
                Write-Warning "[omniroute] user-scope PATH changed during activation; leaving current value untouched."
            }
        } else {
            Write-Warning "[omniroute] user-scope PATH changed during activation; leaving current value untouched."
        }
    }
}

function Test-ImportableConfigSection {
    param([Parameter(Mandatory = $true)][string]$SectionName)

    $normalized = $SectionName.Trim().ToLowerInvariant()
    if ($normalized -eq 'windows') { return $true }
    if ($normalized -eq 'profiles.omniroute_managed.windows') { return $true }
    foreach ($prefix in @('marketplaces.', 'plugins.', 'mcp_servers.', 'projects.')) {
        if ($normalized.StartsWith($prefix, [System.StringComparison]::Ordinal)) { return $true }
    }
    return $false
}

function Get-ImportableConfigBlocks {
    param(
        [Parameter(Mandatory = $true)][string]$ConfigPath,
        [Parameter(Mandatory = $true)][string]$SourceLabel
    )

    $blocks = New-Object System.Collections.Generic.List[object]
    if (-not (Test-Path -LiteralPath $ConfigPath)) { return $blocks }

    $lines = [System.IO.File]::ReadAllLines($ConfigPath)
    $currentName = $null
    $currentLines = New-Object System.Collections.Generic.List[string]

    function Add-ConfigBlock {
        param(
            [AllowNull()][AllowEmptyString()][string]$Name,
            [Parameter(Mandatory = $true)]$Lines
        )
        if ([string]::IsNullOrWhiteSpace($Name)) { return }
        if (-not (Test-ImportableConfigSection -SectionName $Name)) { return }
        $blocks.Add([pscustomobject]@{
            Name = $Name
            Key = $Name.Trim().ToLowerInvariant()
            Text = (($Lines.ToArray()) -join "`r`n").Trim()
            Source = $SourceLabel
        })
    }

    foreach ($line in $lines) {
        $match = [regex]::Match($line, '^\s*\[(.+)\]\s*(?:#.*)?$')
        if ($match.Success) {
            Add-ConfigBlock -Name $currentName -Lines $currentLines
            $currentName = $match.Groups[1].Value.Trim()
            $currentLines = New-Object System.Collections.Generic.List[string]
            $currentLines.Add($line)
            continue
        }
        if ($null -ne $currentName) {
            $currentLines.Add($line)
        }
    }
    Add-ConfigBlock -Name $currentName -Lines $currentLines
    return $blocks
}

function Merge-ConfigBlocks {
    param([Parameter(Mandatory = $true)][AllowNull()][object[]]$Sources)

    $merged = New-Object System.Collections.Generic.List[object]
    foreach ($sourceBlocks in $Sources) {
        if ($null -eq $sourceBlocks) { continue }
        foreach ($block in @($sourceBlocks)) {
            $existingIndex = -1
            for ($i = 0; $i -lt $merged.Count; $i++) {
                if ([string]::Equals($merged[$i].Key, $block.Key, [System.StringComparison]::OrdinalIgnoreCase)) {
                    $existingIndex = $i
                    break
                }
            }
            if ($existingIndex -ge 0) {
                $merged.RemoveAt($existingIndex)
            }
            $merged.Add($block)
        }
    }
    return $merged
}

function ConvertTo-TomlString {
    param([AllowNull()][string]$Value)
    if ($null -eq $Value) { $Value = '' }
    $escaped = $Value.Replace('\', '\\').Replace('"', '\"').Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
    return '"' + $escaped + '"'
}

function ConvertFrom-TomlBasicString {
    param([Parameter(Mandatory = $true)][string]$Value)
    $out = New-Object System.Text.StringBuilder
    for ($i = 0; $i -lt $Value.Length; $i++) {
        $c = $Value[$i]
        if ($c -eq '\' -and $i + 1 -lt $Value.Length) {
            $n = $Value[$i + 1]
            switch ($n) {
                '\' { [void]$out.Append('\'); $i++; continue }
                '"' { [void]$out.Append('"'); $i++; continue }
                'n' { [void]$out.Append("`n"); $i++; continue }
                'r' { [void]$out.Append("`r"); $i++; continue }
                't' { [void]$out.Append("`t"); $i++; continue }
            }
        }
        [void]$out.Append($c)
    }
    return $out.ToString()
}

function Repair-UserProfilePathText {
    param([Parameter(Mandatory = $true)][string]$Text)

    $userProfile = $env:USERPROFILE
    if ([string]::IsNullOrWhiteSpace($userProfile)) { return $Text }

    $singleUser = $userProfile
    $doubleUser = $userProfile.Replace('\', '\\')
    $repaired = $Text

    # Double-escaped TOML strings, e.g. "C:\\Users\\<mojibake>\\AppData\\..."
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]{2}Users[\\]{2}[^"''\r\n]{1,}?[\\]{2}AppData[\\]{2}Roaming[\\]{2}npm',
        ($doubleUser + '\\AppData\\Roaming\\npm'))
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]{2}Users[\\]{2}[^"''\r\n]{1,}?[\\]{2}\.cache[\\]{2}codex-runtimes',
        ($doubleUser + '\\.cache\\codex-runtimes'))
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]{2}Users[\\]{2}[^"''\r\n]{1,}?[\\]{2}\.codex[\\]{2}\.tmp',
        ($doubleUser + '\\.codex\\.tmp'))

    # Single-backslash literal strings and table names.
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]Users[\\][^"''\r\n]{1,}?[\\]AppData[\\]Roaming[\\]npm',
        ($singleUser + '\AppData\Roaming\npm'))
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]Users[\\][^"''\r\n]{1,}?[\\]\.cache[\\]codex-runtimes',
        ($singleUser + '\.cache\codex-runtimes'))
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]Users[\\][^"''\r\n]{1,}?[\\]\.codex[\\]\.tmp',
        ($singleUser + '\.codex\.tmp'))
    $repaired = [regex]::Replace(
        $repaired,
        'C:[\\]Users[\\][^"''\r\n]{1,}?[\\]documents[\\]codex',
        ($singleUser + '\documents\codex'))

    return $repaired
}

function Add-McpStdioShieldIfNeeded {
    param(
        [Parameter(Mandatory = $true)][string]$BlockText,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$NodeExe
    )

    if ($BlockText -match '^\s*url\s*=') { return $BlockText }
    if ($BlockText -match 'mcp-stdio-shield\.mjs') { return $BlockText }

    $cmdMatch = [regex]::Match($BlockText, '(?m)^command\s*=\s*"([^"]+)"\s*$')
    if (-not $cmdMatch.Success) { return $BlockText }

    $rawCommand = $cmdMatch.Groups[1].Value
    $command = ConvertFrom-TomlBasicString -Value $rawCommand
    $isNoisyWrapper = $false
    if ($command -match '(?i)(^|\\)powershell(\.exe)?$') { $isNoisyWrapper = $true }
    if ($command -match '(?i)\.(cmd|bat)$') { $isNoisyWrapper = $true }
    if (-not $isNoisyWrapper) { return $BlockText }

    $shield = Join-Path $ScriptRoot 'tools\mcp-stdio-shield.mjs'
    if (-not (Test-Path -LiteralPath $shield)) { return $BlockText }

    $argsMatch = [regex]::Match($BlockText, '(?m)^args\s*=\s*\[(.*)\]\s*$')
    $innerArgs = ''
    if ($argsMatch.Success) { $innerArgs = $argsMatch.Groups[1].Value.Trim() }

    $newCommandLine = 'command = ' + (ConvertTo-TomlString -Value $NodeExe)
    $newArgsInner = (ConvertTo-TomlString -Value $shield) + ', ' + (ConvertTo-TomlString -Value $command)
    if (-not [string]::IsNullOrWhiteSpace($innerArgs)) {
        $newArgsInner += ', ' + $innerArgs
    }
    $newArgsLine = 'args = [' + $newArgsInner + ']'

    $rewritten = [regex]::Replace($BlockText, '(?m)^command\s*=\s*"[^"]+"\s*$', $newCommandLine, 1)
    if ($argsMatch.Success) {
        $rewritten = [regex]::Replace($rewritten, '(?m)^args\s*=\s*\[.*\]\s*$', $newArgsLine, 1)
    } else {
        $rewritten = [regex]::Replace($rewritten, '(?m)^command\s*=.*$', ($newCommandLine + "`r`n" + $newArgsLine), 1)
    }
    return $rewritten
}

function Get-TopLevelTomlKeys {
    param([Parameter(Mandatory = $true)][string]$BlockText)

    $keys = @{}
    foreach ($line in @($BlockText -split "\r?\n")) {
        if ($line -match '^\s*\[') { continue }
        $match = [regex]::Match($line, '^\s*([A-Za-z0-9_-]+)\s*=')
        if ($match.Success) {
            $keys[$match.Groups[1].Value.ToLowerInvariant()] = $true
        }
    }
    return $keys
}

function Remove-ConflictingInlineChildBlocks {
    param([Parameter(Mandatory = $true)][object[]]$Blocks)

    $inlineKeysByParent = @{}
    foreach ($block in @($Blocks)) {
        $keys = Get-TopLevelTomlKeys -BlockText ([string]$block.Text)
        if ($keys.Count -gt 0) {
            $inlineKeysByParent[[string]$block.Key] = $keys
        }
    }

    $filtered = New-Object System.Collections.Generic.List[object]
    foreach ($block in @($Blocks)) {
        $key = [string]$block.Key
        $lastDot = $key.LastIndexOf('.')
        if ($lastDot -gt 0) {
            $parentKey = $key.Substring(0, $lastDot)
            $childKey = $key.Substring($lastDot + 1).ToLowerInvariant()
            if ($inlineKeysByParent.ContainsKey($parentKey) -and $inlineKeysByParent[$parentKey].ContainsKey($childKey)) {
                Write-Warning ("[omniroute] dropping imported [{0}] from {1}; parent [{2}] already defines inline key '{3}'" -f $block.Name, $block.Source, $parentKey, $childKey)
                continue
            }
        }
        $filtered.Add($block)
    }
    return $filtered
}

function Normalize-ImportedConfigBlocks {
    param(
        [Parameter(Mandatory = $true)][object[]]$Blocks,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$NodeExe
    )

    $normalized = New-Object System.Collections.Generic.List[object]
    foreach ($block in @($Blocks)) {
        $text = Repair-UserProfilePathText -Text ([string]$block.Text)
        if ($text.Length -gt 8000 -or ([string]$block.Name).Length -gt 500) {
            $displayName = [string]$block.Name
            if ($displayName.Length -gt 120) { $displayName = $displayName.Substring(0, 120) + '...' }
            Write-Warning ("[omniroute] dropping oversized imported config section [{0}] from {1}; it still looks corrupted after repair" -f $displayName, $block.Source)
            continue
        }
        $key = $block.Key
        if ($key.StartsWith('mcp_servers.', [System.StringComparison]::OrdinalIgnoreCase) -and
            -not $key.EndsWith('.env', [System.StringComparison]::OrdinalIgnoreCase)) {
            $text = Add-McpStdioShieldIfNeeded -BlockText $text -ScriptRoot $ScriptRoot -NodeExe $NodeExe
        }
        $normalized.Add([pscustomobject]@{
            Name = $block.Name
            Key = $block.Key
            Text = $text.Trim()
            Source = $block.Source
        })
    }
    return (Remove-ConflictingInlineChildBlocks -Blocks $normalized.ToArray())
}

function Format-ImportedConfigBlocks {
    param([Parameter(Mandatory = $true)][object[]]$Blocks)

    if (-not $Blocks -or $Blocks.Count -eq 0) { return '' }

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('# ---- Imported user/runtime tooling sections -----------------------------')
    [void]$sb.AppendLine('# Start-Codex-OmniRoute.ps1 imports selected sections from the previous')
    [void]$sb.AppendLine('# isolated config, the real user config, and the optional overlay file.')
    [void]$sb.AppendLine('# Managed OmniRoute provider/profile sections above are never imported.')
    foreach ($block in $Blocks) {
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine(('# Imported from {0}: [{1}]' -f $block.Source, $block.Name))
        [void]$sb.AppendLine($block.Text)
    }
    return $sb.ToString()
}

# ----------------------------------------------------------------------------
# AppX resolution + activation (same pattern as Start-Codex-Official.ps1)
# ----------------------------------------------------------------------------

function Resolve-CodexAppx {
    if (-not (Test-WindowsHost)) {
        # The verifier and CI run the launcher under pwsh on Linux/macOS for
        # smoke/dry-run; Get-AppxPackage does not exist there. Return a stub
        # so the rest of the script (bridge spin-up + isolated CODEX_HOME
        # seeding) is still exercised. Activation is skipped automatically
        # because `-NoCodex` is the only realistic non-Windows code path.
        return [pscustomobject]@{
            AumId      = 'NON-WINDOWS-STUB!App'
            ExePath    = '/dev/null'
            InstallLoc = '/dev/null'
            Package    = $null
        }
    }
    $pkg = Get-AppxPackage -Name 'OpenAI.Codex' -ErrorAction SilentlyContinue
    if (-not $pkg) {
        throw "Official Codex Microsoft Store app is not installed (Get-AppxPackage OpenAI.Codex returned nothing). Install it from the Microsoft Store first."
    }
    if ($pkg -is [array]) { $pkg = $pkg[0] }

    $candidates = @(
        (Join-Path $pkg.InstallLocation 'app\Codex.exe'),
        (Join-Path $pkg.InstallLocation 'Codex.exe')
    )
    $exe = $null
    foreach ($c in $candidates) { if (Test-Path -LiteralPath $c) { $exe = $c; break } }
    if (-not $exe) {
        throw "Found Codex package at '$($pkg.InstallLocation)' but could not locate Codex.exe (looked in app\\Codex.exe and Codex.exe)."
    }

    $appId = 'App'
    try {
        $manifestPath = Join-Path $pkg.InstallLocation 'AppxManifest.xml'
        if (Test-Path -LiteralPath $manifestPath) {
            [xml]$manifest = Get-Content -LiteralPath $manifestPath -Raw
            $appNode = $manifest.Package.Applications.Application
            if ($appNode -and $appNode.Id) { $appId = $appNode.Id }
        }
    } catch { }

    return [pscustomobject]@{
        AumId      = "$($pkg.PackageFamilyName)!$appId"
        ExePath    = $exe
        InstallLoc = $pkg.InstallLocation
        Package    = $pkg
    }
}

function Start-CodexViaAppx {
    param(
        [Parameter(Mandatory = $true)][string]$AumId,
        [string]$Arguments = ''
    )

    if (-not ('CodexOmniRouteAppxActivator' -as [type])) {
        Add-Type -TypeDefinition @'
using System;
using System.Runtime.InteropServices;

[ComImport, Guid("45BA127D-10A8-46EA-8AB7-56EA9078943C")]
public class CodexOmniRouteApplicationActivationManager {}

[Flags]
public enum CodexOmniRouteActivateOptions {
    None = 0,
    DesignMode = 1,
    NoErrorUI = 2,
    NoSplashScreen = 4
}

[ComImport, Guid("2e941141-7f97-4756-ba1d-9decde894a3d"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
public interface ICodexOmniRouteApplicationActivationManager {
    [PreserveSig]
    int ActivateApplication(
        [MarshalAs(UnmanagedType.LPWStr)] string appUserModelId,
        [MarshalAs(UnmanagedType.LPWStr)] string arguments,
        CodexOmniRouteActivateOptions options,
        out uint processId);
}

public static class CodexOmniRouteAppxActivator {
    public static int Activate(string appUserModelId, string arguments, out uint processId) {
        var manager = (ICodexOmniRouteApplicationActivationManager)new CodexOmniRouteApplicationActivationManager();
        return manager.ActivateApplication(
            appUserModelId,
            arguments ?? "",
            CodexOmniRouteActivateOptions.NoErrorUI,
            out processId);
    }
}
'@
    }

    [uint32]$activatedPid = 0
    $hr = [CodexOmniRouteAppxActivator]::Activate($AumId, $Arguments, [ref]$activatedPid)
    if ($hr -ne 0) {
        throw ("AppX activation failed for {0} (HRESULT 0x{1:X8})." -f $AumId, $hr)
    }
    return $activatedPid
}

# ----------------------------------------------------------------------------
# Port + bridge helpers
# ----------------------------------------------------------------------------

function Test-PortFree {
    param([int]$Port)
    try {
        $listener = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Loopback, $Port)
        $listener.Start()
        $listener.Stop()
        return $true
    } catch {
        return $false
    }
}

function Find-FreePort {
    param([int]$Preferred, [int]$Range = 50)
    for ($p = $Preferred; $p -lt $Preferred + $Range; $p++) {
        if (Test-PortFree -Port $p) { return $p }
    }
    throw "No free port found in range [$Preferred, $($Preferred + $Range))."
}

function Find-NodeExe {
    $cmd = Get-Command node -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    throw "node.exe not found on PATH. Install Node.js >= 18.18 from https://nodejs.org/."
}

function Resolve-LocalCodexCli {
    $candidates = New-Object System.Collections.Generic.List[string]
    if ($env:LOCALAPPDATA) {
        $candidates.Add((Join-Path $env:LOCALAPPDATA 'OpenAI\Codex\bin\codex.exe'))
    }
    $cmd = Get-Command codex -ErrorAction SilentlyContinue
    if ($cmd -and $cmd.Source) {
        $candidates.Add($cmd.Source)
    }
    foreach ($candidate in $candidates) {
        if (-not $candidate) { continue }
        if ($candidate -match '\\WindowsApps\\') { continue }
        if (Test-Path -LiteralPath $candidate) { return $candidate }
    }
    throw "Could not find launchable local codex.exe. Expected %LOCALAPPDATA%\OpenAI\Codex\bin\codex.exe."
}

function Invoke-ConfigRepairIfNeeded {
    param(
        [Parameter(Mandatory = $true)][string]$OfficialHome,
        [Parameter(Mandatory = $true)][string]$ScriptRoot
    )
    $repairTool = Join-Path $ScriptRoot 'tools\Repair-CodexConfig.ps1'
    if (-not (Test-Path -LiteralPath $repairTool)) { return }
    try {
        & $repairTool -CodexHome $OfficialHome -Quiet
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "[omniroute] config repair helper exited with code $LASTEXITCODE"
        }
    } catch {
        Write-Warning "[omniroute] config repair helper failed: $($_.Exception.Message)"
    }
}

function Wait-ForBridgeHealth {
    # NOTE: do not name a param $Host -- $Host is a PowerShell automatic variable.
    param([string]$BridgeHost, [int]$Port, [int]$TimeoutSec = 20)
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    $url = "http://{0}:{1}/healthz" -f $BridgeHost, $Port
    while ((Get-Date) -lt $deadline) {
        try {
            $resp = Invoke-RestMethod -Uri $url -TimeoutSec 2 -ErrorAction Stop
            if ($resp.ok) { return $resp }
        } catch { Start-Sleep -Milliseconds 250 }
    }
    throw ("Bridge /healthz did not respond within {0}s on {1}" -f $TimeoutSec, $url)
}

function Stop-ManagedBridge {
    param([string]$PidPath)
    if (-not (Test-Path -LiteralPath $PidPath)) { return }
    try {
        $pidText = (Get-Content -LiteralPath $PidPath -Raw -ErrorAction Stop).Trim()
    } catch { return }
    if (-not ($pidText -match '^\d+$')) { return }
    $existingPid = [int]$pidText
    try {
        $proc = Get-Process -Id $existingPid -ErrorAction Stop
        if ($proc.ProcessName -match '^node') {
            Stop-Process -Id $existingPid -Force -ErrorAction SilentlyContinue
            Write-Host "[omniroute] stopped previous bridge (pid=$existingPid)"
        }
    } catch { } # process already gone
    Remove-Item -LiteralPath $PidPath -Force -ErrorAction SilentlyContinue
}

function Stop-ManagedApplyPatchRewriter {
    param([string]$PidPath)
    if (-not (Test-Path -LiteralPath $PidPath)) { return }
    try {
        $pidText = (Get-Content -LiteralPath $PidPath -Raw -ErrorAction Stop).Trim()
    } catch { return }
    if (-not ($pidText -match '^\d+$')) {
        Remove-Item -LiteralPath $PidPath -Force -ErrorAction SilentlyContinue
        return
    }
    $existingPid = [int]$pidText
    try {
        $proc = Get-Process -Id $existingPid -ErrorAction Stop
        if ($proc.ProcessName -match '^node') {
            Stop-Process -Id $existingPid -Force -ErrorAction SilentlyContinue
            Write-Host "[omniroute] stopped apply_patch rewriter (pid=$existingPid)"
        }
    } catch { }
    Remove-Item -LiteralPath $PidPath -Force -ErrorAction SilentlyContinue
}

function Start-ApplyPatchRewriter {
    param(
        [Parameter(Mandatory = $true)][string]$NodeExe,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$IsolatedHome,
        [Parameter(Mandatory = $true)][string]$LocalCodexExe,
        [Parameter(Mandatory = $true)][string]$PidPath,
        [Parameter(Mandatory = $true)][string]$LogPath
    )

    $rewriterScript = Join-Path $ScriptRoot 'tools\apply_patch-rewriter.mjs'
    if (-not (Test-Path -LiteralPath $rewriterScript)) {
        throw "apply_patch rewriter script not found: $rewriterScript"
    }

    Stop-ManagedApplyPatchRewriter -PidPath $PidPath
    "[$(Get-Date -Format o)] apply_patch rewriter starting node=$NodeExe codex=$LocalCodexExe home=$IsolatedHome" |
        Out-File -LiteralPath $LogPath -Encoding UTF8 -Append

    $startArgs = @{
        FilePath         = $NodeExe
        ArgumentList     = @($rewriterScript, '--home', $IsolatedHome, '--codex', $LocalCodexExe)
        WorkingDirectory = $ScriptRoot
        PassThru         = $true
    }
    if (Test-WindowsHost) {
        $startArgs['WindowStyle'] = 'Hidden'
    }
    $proc = Start-Process @startArgs
    if (-not $proc) {
        throw "[omniroute] failed to start apply_patch rewriter process"
    }
    Set-Content -LiteralPath $PidPath -Value $proc.Id -Encoding ASCII
    Write-Host "[omniroute] apply_patch rewriter running (pid=$($proc.Id), local codex=$LocalCodexExe)"
}

function Invoke-McpRuntimeProbe {
    param(
        [Parameter(Mandatory = $true)][string]$NodeExe,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$ConfigPath
    )

    $probeScript = Join-Path $ScriptRoot 'tools\mcp_probe.mjs'
    if (-not (Test-Path -LiteralPath $probeScript)) {
        Write-Warning "[omniroute] MCP probe script not found: $probeScript"
        return
    }

    $raw = & $NodeExe $probeScript --config $ConfigPath --timeout-ms 8000 --json 2>&1
    $exit = $LASTEXITCODE
    $joined = ($raw | Out-String)
    if ($exit -ne 0) {
        Write-Warning "[omniroute] MCP probe exited with code $exit`: $($joined.Trim())"
        return
    }

    try {
        $parsed = $joined | ConvertFrom-Json -ErrorAction Stop
    } catch {
        Write-Warning "[omniroute] MCP probe returned non-JSON output: $($joined.Trim())"
        return
    }

    $bad = @()
    $coreBad = @()
    $discoverableStatuses = @('tools_listed', 'callable')
    foreach ($result in @($parsed.results)) {
        if ($discoverableStatuses -contains [string]$result.status) { continue }
        $bad += ("{0}={1}" -f $result.name, $result.status)
        if ($result.name -in @('magic', 'shadcn')) {
            $coreBad += ("{0}={1}" -f $result.name, $result.status)
        }
    }
    $listedCount = @($parsed.results | Where-Object { $discoverableStatuses -contains [string]$_.status }).Count
    $callableCount = @($parsed.results | Where-Object { $_.status -eq 'callable' }).Count
    $urlCount = @($parsed.results | Where-Object { $_.transport -eq 'http' }).Count
    if ($bad.Count -eq 0) {
        Write-Host ("[omniroute] MCP runtime probe ok (discoverable={0}, callable={1}, url={2})" -f $listedCount, $callableCount, $urlCount)
    } elseif ($coreBad.Count -gt 0) {
        throw ("[omniroute] core frontend MCP probe failed: {0}" -f ($coreBad -join ', '))
    } else {
        Write-Warning ("[omniroute] MCP runtime probe found non-core failures: {0}" -f ($bad -join ', '))
    }
}

# ----------------------------------------------------------------------------
# Codex home resolution
# ----------------------------------------------------------------------------

function Get-OfficialCodexHome {
    # USERPROFILE is Windows-only. On non-Windows hosts (CI / verifier
    # smoke), fall back to $HOME so the launcher and the bridge agree on
    # which directory holds the user's real Codex profile. Codex Desktop
    # itself only ever runs on Windows.
    if ($env:USERPROFILE) {
        return (Join-Path $env:USERPROFILE '.codex')
    }
    if ($env:HOME) {
        return (Join-Path $env:HOME '.codex')
    }
    throw "Cannot resolve Codex home directory: neither USERPROFILE nor HOME is set."
}

# ----------------------------------------------------------------------------
# Isolated CODEX_HOME: write managed config + safe user/runtime overlays
# ----------------------------------------------------------------------------

function Build-IsolatedConfigToml {
    param(
        [Parameter(Mandatory = $true)][int]$Port,
        [bool]$IncludeFreeform = $true,
        [object[]]$ImportedConfigBlocks = @()
    )

    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('# Codex OmniRoute -- isolated CODEX_HOME config.')
    [void]$sb.AppendLine('# This file is regenerated by Start-Codex-OmniRoute.ps1 on every')
    [void]$sb.AppendLine('# launch and lives ONLY in the isolated .codex-omniroute-home/')
    [void]$sb.AppendLine('# directory next to the launcher. The managed OmniRoute provider')
    [void]$sb.AppendLine('# below is written by the launcher; selected tooling sections are')
    [void]$sb.AppendLine('# imported later from real/overlay config. Your real')
    [void]$sb.AppendLine('# %USERPROFILE%\.codex\config.toml is NOT touched.')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('model_provider = "omniroute_bridge"')
    [void]$sb.AppendLine('model = "gpt-5.4"')
    [void]$sb.AppendLine('model_reasoning_effort = "xhigh"')
    [void]$sb.AppendLine('profile = "omniroute_managed"')
    [void]$sb.AppendLine('suppress_unstable_features_warning = true')
    [void]$sb.AppendLine('[features]')
    [void]$sb.AppendLine('builtin_mcp = true')
    [void]$sb.AppendLine('enable_mcp_apps = true')
    [void]$sb.AppendLine('tool_search_always_defer_mcp_tools = false')
    if ($IncludeFreeform) {
        # Cheap safety net for the rare case where a future Codex update
        # regresses apply_patch.bat under AppX activation.
        [void]$sb.AppendLine('apply_patch_freeform = true')
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('[model_providers.omniroute_bridge]')
    [void]$sb.AppendLine('name = "OmniRoute Bridge"')
    [void]$sb.AppendLine(('base_url = "http://127.0.0.1:{0}/v1"' -f $Port))
    [void]$sb.AppendLine('wire_api = "responses"')
    [void]$sb.AppendLine('requires_openai_auth = true')
    [void]$sb.AppendLine('supports_websockets = false')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('[profiles.omniroute_managed]')
    [void]$sb.AppendLine('model_provider = "omniroute_bridge"')
    [void]$sb.AppendLine('model = "gpt-5.4"')
    [void]$sb.AppendLine('model_reasoning_effort = "xhigh"')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('[profiles.omniroute_managed.features]')
    [void]$sb.AppendLine('builtin_mcp = true')
    [void]$sb.AppendLine('enable_mcp_apps = true')
    [void]$sb.AppendLine('tool_search_always_defer_mcp_tools = false')
    if ($IncludeFreeform) {
        [void]$sb.AppendLine('apply_patch_freeform = true')
    }
    $imported = Format-ImportedConfigBlocks -Blocks $ImportedConfigBlocks
    if ($imported) {
        [void]$sb.Append($imported)
    }
    return $sb.ToString()
}

function Invoke-OmniRouteCatalog {
    param(
        [Parameter(Mandatory = $true)][string]$NodeExe,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$IsolatedHome
    )

    # Loads the OmniRoute MCP/skills catalog (remote URL with fallback to a
    # last-known-good cache and finally the in-repo default-mcp-catalog.json
    # bundle) and turns each MCP entry into an importable [mcp_servers.<name>]
    # block plus writes any skill entries into $IsolatedHome\skills\<name>\SKILL.md.
    #
    # The bundle ships with the fork so a brand-new clone gets a useful MCP
    # baseline on first launch with zero network and zero per-user setup.
    # Setting OMNIROUTE_CATALOG_URL turns on central updates; an absent or
    # unreachable URL silently falls back through cache to bundle.
    # OMNIROUTE_CATALOG_DISABLED=1 disables the whole feature.

    $catalogScript = Join-Path $ScriptRoot $OmniRouteCatalogScriptRelPath
    if (-not (Test-Path -LiteralPath $catalogScript)) {
        Write-Warning "[omniroute] catalog helper not found: $catalogScript"
        return @()
    }

    $bundlePath = Join-Path $ScriptRoot $OmniRouteCatalogBundleFileName
    $cachePath  = Join-Path $ScriptRoot $OmniRouteCatalogCacheFileName
    $tomlPath   = Join-Path $IsolatedHome $OmniRouteCatalogTomlFileName

    $argList = @(
        $catalogScript,
        '--toml-out',      $tomlPath,
        '--isolated-home', $IsolatedHome,
        '--bundle',        $bundlePath,
        '--cache',         $cachePath,
        '--timeout-ms',    '5000'
    )
    if (-not [string]::IsNullOrWhiteSpace($env:OMNIROUTE_CATALOG_URL)) {
        $argList += @('--catalog-url', $env:OMNIROUTE_CATALOG_URL)
    }
    if (-not [string]::IsNullOrWhiteSpace($env:OMNIROUTE_API_KEY)) {
        $argList += @('--api-key', $env:OMNIROUTE_API_KEY)
    }
    if ($env:OMNIROUTE_CATALOG_DISABLED -eq '1') {
        $argList += @('--disabled')
    }

    $raw = & $NodeExe @argList 2>&1
    $exit = $LASTEXITCODE
    $joined = ($raw | Out-String)
    if ($exit -ne 0) {
        Write-Warning "[omniroute] catalog helper exited with code $exit`: $($joined.Trim())"
        return @()
    }

    try {
        $status = $joined | ConvertFrom-Json -ErrorAction Stop
    } catch {
        Write-Warning "[omniroute] catalog helper returned non-JSON: $($joined.Trim())"
        return @()
    }

    $source         = if ($status.source) { [string]$status.source } else { 'unknown' }
    $catalogVersion = if ($status.catalog_version) { [string]$status.catalog_version } else { '' }
    $mcpCount       = [int]$status.mcp_count
    $skillCount     = [int]$status.skill_count
    Write-Host ("[omniroute] catalog source={0} version={1} mcp={2} skills={3}" -f $source, $catalogVersion, $mcpCount, $skillCount)
    if ($status.warnings) {
        foreach ($w in @($status.warnings)) {
            Write-Warning "[omniroute] catalog: $w"
        }
    }

    if ($mcpCount -le 0) { return @() }
    if (-not (Test-Path -LiteralPath $tomlPath)) { return @() }
    return @(Get-ImportableConfigBlocks -ConfigPath $tomlPath -SourceLabel 'omniroute catalog')
}

function Seed-IsolatedCodexHome {
    param(
        [Parameter(Mandatory = $true)][string]$IsolatedHome,
        [Parameter(Mandatory = $true)][string]$OfficialHome,
        [Parameter(Mandatory = $true)][string]$ScriptRoot,
        [Parameter(Mandatory = $true)][string]$NodeExe,
        [Parameter(Mandatory = $true)][int]$Port,
        [bool]$IncludeFreeform = $true,
        [AllowNull()][string]$OverlayConfigPath = $null
    )

    $previousIsolatedConfig = Join-Path $IsolatedHome 'config.toml'
    $previousBlocks = @(Get-ImportableConfigBlocks -ConfigPath $previousIsolatedConfig -SourceLabel 'previous isolated config')
    $officialConfig = Join-Path $OfficialHome 'config.toml'
    $officialBlocks = @(Get-ImportableConfigBlocks -ConfigPath $officialConfig -SourceLabel 'real user config')
    $repairConfig = Join-Path $OfficialHome $KnownGoodConfigBackupFileName
    $repairBlocks = @()
    if (Test-Path -LiteralPath $repairConfig) {
        $repairBlocks = @(Get-ImportableConfigBlocks -ConfigPath $repairConfig -SourceLabel 'known-good config backup')
    }
    $overlayBlocks = @()
    if ($OverlayConfigPath) {
        $overlayBlocks = @(Get-ImportableConfigBlocks -ConfigPath $OverlayConfigPath -SourceLabel 'overlay config')
    }

    # The catalog helper writes skills directly into $IsolatedHome\skills\;
    # make sure the directory exists before we invoke it. The block below
    # also creates it for state seeding, so this is idempotent.
    New-Item -ItemType Directory -Path $IsolatedHome -Force | Out-Null

    $catalogBlocks = @(Invoke-OmniRouteCatalog `
        -NodeExe $NodeExe `
        -ScriptRoot $ScriptRoot `
        -IsolatedHome $IsolatedHome)

    # Merge order is significant: later sources override earlier ones on
    # name collision. Previous launches sit at the bottom so stale catalog
    # entries get refreshed; the catalog supplies the centrally-managed
    # defaults; the user's real config overrides catalog defaults; the
    # known-good backup and overlay win last.
    $importedBlocks = Merge-ConfigBlocks -Sources @($previousBlocks, $catalogBlocks, $officialBlocks, $repairBlocks, $overlayBlocks)
    $importedBlocks = Normalize-ImportedConfigBlocks -Blocks $importedBlocks -ScriptRoot $ScriptRoot -NodeExe $NodeExe

    # Keep the isolated home persistent. Codex Desktop stores visible chat
    # history and runtime state across state_5.sqlite*, logs_2.sqlite*,
    # sessions/, session_index.jsonl, and .codex-global-state.json. Earlier
    # launchers deleted the whole directory on every start, which guaranteed
    # a clean config read but also guaranteed an empty chat list.
    New-Item -ItemType Directory -Path $IsolatedHome -Force | Out-Null

    # Seed auth.json (OAuth tokens) from the user's real profile so Codex
    # Desktop boots already logged in as the user. This is the difference
    # between Variant 3 and PR #3's API-key sentinel: we keep the real
    # OAuth tokens, so fast mode / ChatGPT credits keep working.
    $officialAuth = Join-Path $OfficialHome 'auth.json'
    $isolatedAuth = Join-Path $IsolatedHome 'auth.json'
    if (Test-Path -LiteralPath $officialAuth) {
        try {
            Copy-Item -LiteralPath $officialAuth -Destination $isolatedAuth -Force
            Write-Host "[omniroute] seeded auth.json from $officialAuth"
        } catch {
            Write-Warning "[omniroute] failed to copy auth.json: $($_.Exception.Message). Desktop may show the login screen."
        }
    } else {
        Write-Warning "[omniroute] no $officialAuth -- isolated CODEX_HOME starts without auth.json. Launch the official Codex once and sign in, then re-run."
    }

    # Seed models_cache.json if present so the bridge's /v1/models route
    # has data on first load.
    $officialModels = Join-Path $OfficialHome 'models_cache.json'
    $isolatedModels = Join-Path $IsolatedHome 'models_cache.json'
    if (Test-Path -LiteralPath $officialModels) {
        try {
            Copy-Item -LiteralPath $officialModels -Destination $isolatedModels -Force
            Write-Host "[omniroute] seeded models_cache.json from $officialModels"
        } catch {
            Write-Warning "[omniroute] failed to copy models_cache.json: $($_.Exception.Message)"
        }
    }

    # Write the isolated config.toml from the managed block plus imported
    # user/runtime tooling sections.
    $isolatedConfig = Join-Path $IsolatedHome 'config.toml'
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    $content = Build-IsolatedConfigToml -Port $Port -IncludeFreeform:$IncludeFreeform -ImportedConfigBlocks $importedBlocks
    [System.IO.File]::WriteAllText($isolatedConfig, $content, $utf8NoBom)
    Write-Host "[omniroute] wrote isolated config.toml at $isolatedConfig"
    if ($importedBlocks.Count -gt 0) {
        $mcpCount = @($importedBlocks | Where-Object { $_.Name.Trim().ToLowerInvariant().StartsWith('mcp_servers.', [System.StringComparison]::Ordinal) }).Count
        $pluginCount = @($importedBlocks | Where-Object { $_.Name.Trim().ToLowerInvariant().StartsWith('plugins.', [System.StringComparison]::Ordinal) }).Count
        $marketCount = @($importedBlocks | Where-Object { $_.Name.Trim().ToLowerInvariant().StartsWith('marketplaces.', [System.StringComparison]::Ordinal) }).Count
        Write-Host ("[omniroute] imported config sections: marketplaces={0}, plugins={1}, mcp_sections={2}, total={3}" -f $marketCount, $pluginCount, $mcpCount, $importedBlocks.Count)
    }

    # Write a stamp file that records the isolated dir contents at seed
    # time. The bridge reads this on /healthz to compute
    # desktop_codex_home_honored: if Codex Desktop honored CODEX_HOME, it
    # will eventually create state_5.sqlite (or modify auth.json /
    # models_cache.json) inside the isolated dir, and the stamp's mtime
    # snapshot will diverge from the current dir.
    $stampPath = Join-Path $IsolatedHome '.omniroute-seed.json'
    $stamp = [ordered]@{
        seeded_at_utc = (Get-Date).ToUniversalTime().ToString('o')
        bridge_port   = $Port
        files = @()
    }
    Get-ChildItem -LiteralPath $IsolatedHome -Force -File -ErrorAction SilentlyContinue | ForEach-Object {
        # The stamp file itself is excluded so writing it doesn't change
        # the stamp on subsequent reads.
        if ($_.Name -eq '.omniroute-seed.json') { return }
        $stamp.files += [ordered]@{
            name  = $_.Name
            size  = $_.Length
            mtime = $_.LastWriteTimeUtc.ToString('o')
        }
    }
    $stampJson = $stamp | ConvertTo-Json -Depth 5
    [System.IO.File]::WriteAllText($stampPath, $stampJson, $utf8NoBom)
}

function Remove-IsolatedCodexHome {
    param([Parameter(Mandatory = $true)][string]$IsolatedHome)
    if (-not (Test-Path -LiteralPath $IsolatedHome)) { return }
    try {
        Remove-Item -LiteralPath $IsolatedHome -Recurse -Force -ErrorAction Stop
        Write-Host "[omniroute] removed isolated CODEX_HOME at $IsolatedHome"
    } catch {
        Write-Warning "[omniroute] could not fully remove isolated CODEX_HOME at $IsolatedHome -- $($_.Exception.Message)"
    }
}

# ----------------------------------------------------------------------------
# Legacy PR-#3 / PR-#2 cleanup in the user's real ~/.codex
#
# Earlier versions of this launcher wrote a managed-block into the user's
# real ~/.codex/config.toml and replaced their real ~/.codex/auth.json
# with an API-key sentinel. Variant 3 does neither. To make the transition
# safe for upgrading users, we sweep up any leftover artifacts from those
# versions on every launch and on -Restore.
# ----------------------------------------------------------------------------

function Remove-LegacyManagedBlockText {
    param([string]$Content)
    if ($null -eq $Content -or $Content.Length -eq 0) { return $Content }
    $pattern = '(?ms)^[\t ]*' + [regex]::Escape($LegacyManagedBlockBegin) + '[\s\S]*?' + [regex]::Escape($LegacyManagedBlockEnd) + '[\t ]*\r?\n?'
    $stripped = [regex]::Replace($Content, $pattern, '')
    return [regex]::Replace($stripped, '(\r?\n){3,}', "`r`n`r`n")
}

function Test-IsLegacyManagedAuth {
    param([string]$Content)
    if ([string]::IsNullOrWhiteSpace($Content)) { return $false }
    try { $obj = $Content | ConvertFrom-Json -ErrorAction Stop } catch { return $false }
    if (-not $obj) { return $false }
    $hasMarker = $false
    try {
        if ($obj.PSObject.Properties.Name -contains '_codex_omniroute') {
            $marker = $obj.'_codex_omniroute'
            if ($marker -and $marker.managed) { $hasMarker = $true }
        }
    } catch { }
    $hasSentinel = $false
    try {
        if ($obj.PSObject.Properties.Name -contains 'OPENAI_API_KEY') {
            if ([string]$obj.OPENAI_API_KEY -eq $LegacyManagedAuthSentinelKey) {
                $hasSentinel = $true
            }
        }
    } catch { }
    return ($hasMarker -or $hasSentinel)
}

function Invoke-LegacyCleanup {
    param([Parameter(Mandatory = $true)][string]$OfficialHome)

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)

    # 1. config.toml: if a backup from PR-#2 exists, restore it; else strip
    #    any orphan managed block in place.
    $configPath = Join-Path $OfficialHome 'config.toml'
    $configBackup = Join-Path $OfficialHome 'config.toml.codex-omniroute-backup'
    if (Test-Path -LiteralPath $configBackup) {
        try {
            $backup = Get-Content -LiteralPath $configBackup -Raw
            if ($null -eq $backup) { $backup = '' }
            if ($backup.Length -eq 0) {
                if (Test-Path -LiteralPath $configPath) {
                    # Backup is the "no original existed" sentinel from PR #2.
                    $existing = Get-Content -LiteralPath $configPath -Raw -ErrorAction SilentlyContinue
                    if ($existing -and $existing.Contains($LegacyManagedBlockBegin)) {
                        Remove-Item -LiteralPath $configPath -Force
                        Write-Host "[omniroute] legacy cleanup: removed managed-only config.toml (no original existed)"
                    }
                }
            } else {
                [System.IO.File]::WriteAllText($configPath, $backup, $utf8NoBom)
                Write-Host "[omniroute] legacy cleanup: restored original config.toml from $configBackup"
            }
        } catch {
            Write-Warning "[omniroute] legacy cleanup: failed to restore config.toml from $configBackup -- $($_.Exception.Message)"
        }
        Remove-Item -LiteralPath $configBackup -Force -ErrorAction SilentlyContinue
    } elseif (Test-Path -LiteralPath $configPath) {
        try {
            $existing = Get-Content -LiteralPath $configPath -Raw -ErrorAction SilentlyContinue
            if ($existing -and $existing.Contains($LegacyManagedBlockBegin)) {
                $stripped = Remove-LegacyManagedBlockText -Content $existing
                [System.IO.File]::WriteAllText($configPath, $stripped, $utf8NoBom)
                Write-Host "[omniroute] legacy cleanup: stripped orphan managed block from $configPath"
            }
        } catch {
            Write-Warning "[omniroute] legacy cleanup: failed to strip managed block in $configPath -- $($_.Exception.Message)"
        }
    }

    # 2. auth.json: if a backup from PR-#3 exists, restore it; else if the
    #    live file looks like our legacy sentinel, delete it.
    $authPath = Join-Path $OfficialHome 'auth.json'
    $authBackup = Join-Path $OfficialHome 'auth.json.codex-omniroute-backup'
    if (Test-Path -LiteralPath $authBackup) {
        try {
            $backup = Get-Content -LiteralPath $authBackup -Raw
            if ($null -eq $backup) { $backup = '' }
            if ($backup.Length -eq 0) {
                if (Test-Path -LiteralPath $authPath) {
                    $existing = Get-Content -LiteralPath $authPath -Raw -ErrorAction SilentlyContinue
                    if ($null -ne $existing -and (Test-IsLegacyManagedAuth -Content $existing)) {
                        Remove-Item -LiteralPath $authPath -Force
                        Write-Host "[omniroute] legacy cleanup: removed sentinel auth.json (no original existed)"
                    }
                }
            } else {
                [System.IO.File]::WriteAllText($authPath, $backup, $utf8NoBom)
                Write-Host "[omniroute] legacy cleanup: restored original auth.json from $authBackup"
            }
        } catch {
            Write-Warning "[omniroute] legacy cleanup: failed to restore auth.json from $authBackup -- $($_.Exception.Message)"
        }
        Remove-Item -LiteralPath $authBackup -Force -ErrorAction SilentlyContinue
    } elseif (Test-Path -LiteralPath $authPath) {
        try {
            $existing = Get-Content -LiteralPath $authPath -Raw -ErrorAction SilentlyContinue
            if ($null -ne $existing -and (Test-IsLegacyManagedAuth -Content $existing)) {
                Remove-Item -LiteralPath $authPath -Force
                Write-Host "[omniroute] legacy cleanup: removed orphan sentinel auth.json $authPath"
            }
        } catch {
            Write-Warning "[omniroute] legacy cleanup: failed to inspect/remove sentinel auth.json -- $($_.Exception.Message)"
        }
    }
}

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------

$scriptRoot = if ($PSScriptRoot) { $PSScriptRoot } else { (Split-Path -Parent $MyInvocation.MyCommand.Path) }
if (-not $scriptRoot) { $scriptRoot = (Get-Location).Path }
$bridgeScript = Join-Path $scriptRoot 'codex-openai-omniroute-bridge.mjs'
if (-not (Test-Path -LiteralPath $bridgeScript)) {
    throw "Bridge script not found: $bridgeScript"
}
$bridgePid = Join-Path $scriptRoot 'bridge.pid'
$bridgeLog = Join-Path $scriptRoot 'bridge.log'
$applyPatchRewriterPid = Join-Path $scriptRoot $ApplyPatchRewriterPidFileName
$applyPatchRewriterLog = Join-Path $scriptRoot $ApplyPatchRewriterLogFileName
$configOverlay = Join-Path $scriptRoot $ConfigOverlayFileName

$officialHome = Get-OfficialCodexHome
$isolatedHome = Join-Path $scriptRoot $IsolatedHomeDirName
$taskkillShimDir = Join-Path $isolatedHome 'bin'

# ---- Restore mode ---------------------------------------------------------

if ($Restore) {
    Stop-ManagedBridge -PidPath $bridgePid
    Stop-ManagedApplyPatchRewriter -PidPath $applyPatchRewriterPid
    Clear-StaleUserCodexHomeOverride -IsolatedHome $isolatedHome
    Clear-StaleTaskkillShimPathOverride -ShimDir $taskkillShimDir
    Remove-IsolatedCodexHome -IsolatedHome $isolatedHome
    # Reverse any leftover PR-#3 artifacts in the user's real ~/.codex.
    Invoke-LegacyCleanup -OfficialHome $officialHome
    Write-Host "[omniroute] restore complete. Codex now uses your real ~/.codex profile (no bridge, no isolated home)."
    exit 0
}

# ---- Pre-flight -----------------------------------------------------------

$appx = Resolve-CodexAppx
$nodeExe = Find-NodeExe
$localCodexExe = Resolve-LocalCodexCli
$port = Find-FreePort -Preferred $BridgePort

Write-Host "[omniroute] Codex AumId:    $($appx.AumId)"
Write-Host "[omniroute] node:           $nodeExe"
Write-Host "[omniroute] local codex:    $localCodexExe"
Write-Host "[omniroute] bridge port:    $port"
Write-Host "[omniroute] official home:  $officialHome"
Write-Host "[omniroute] isolated home:  $isolatedHome"

if (-not $NoConfigRepair) {
    Invoke-ConfigRepairIfNeeded -OfficialHome $officialHome -ScriptRoot $scriptRoot
}

# Warn if Codex is already running -- the AppX broker will activate the
# existing instance, which won't re-read config.toml.
$existingCodex = Get-Process -Name 'Codex' -ErrorAction SilentlyContinue
if ($existingCodex) {
    Write-Warning "[omniroute] Codex is already running (pid=$($existingCodex.Id -join ',')). Quit it (right-click tray icon -> Quit) before re-launching so the new CODEX_HOME takes effect."
}

if ($DryRun) {
    Write-Host "[omniroute] DryRun -- not seeding isolated home, not starting bridge, not launching Codex."
    [pscustomobject]@{
        Mode               = 'omniroute'
        AumId              = $appx.AumId
        BridgePort         = $port
        BridgeScript       = $bridgeScript
        ConfigOverlay      = $configOverlay
        ConfigOverlayFound = (Test-Path -LiteralPath $configOverlay)
        OfficialHome       = $officialHome
        IsolatedHome       = $isolatedHome
        LocalCodexExe      = $localCodexExe
        FreeformApplyPatch = (-not $NoFreeformApplyPatch)
        ApplyPatchRewriter = (-not $NoApplyPatchRewriter)
        McpProbe           = (-not $NoMcpProbe)
        UserCodexHomeRestoreTimeoutSec = $UserCodexHomeRestoreTimeoutSec
        OpenProject        = $OpenProject
        DryRun             = $true
    } | Format-List
    exit 0
}

# ---- Sweep any legacy PR-#3 / PR-#2 artifacts -----------------------------
#
# This is a one-shot reverse-of-old-architecture for users upgrading from
# earlier versions of the repo. It is safe to run on a clean profile: it
# only acts if it actually finds a managed block, a sentinel auth.json,
# or one of the backup files.

Invoke-LegacyCleanup -OfficialHome $officialHome
Clear-StaleTaskkillShimPathOverride -ShimDir $taskkillShimDir

# ---- Seed isolated CODEX_HOME ---------------------------------------------

Seed-IsolatedCodexHome `
    -IsolatedHome    $isolatedHome `
    -OfficialHome    $officialHome `
    -ScriptRoot      $scriptRoot `
    -NodeExe         $nodeExe `
    -Port            $port `
    -IncludeFreeform:(-not $NoFreeformApplyPatch) `
    -OverlayConfigPath $configOverlay

$compiledTaskkillShimDir = Ensure-TaskkillQuietShim -IsolatedHome $isolatedHome -ScriptRoot $scriptRoot
if ($compiledTaskkillShimDir) {
    $taskkillShimDir = $compiledTaskkillShimDir
}

if (-not $NoMcpProbe) {
    Invoke-McpRuntimeProbe -NodeExe $nodeExe -ScriptRoot $scriptRoot -ConfigPath (Join-Path $isolatedHome 'config.toml')
}

if (-not $NoApplyPatchRewriter) {
    Start-ApplyPatchRewriter `
        -NodeExe $nodeExe `
        -ScriptRoot $scriptRoot `
        -IsolatedHome $isolatedHome `
        -LocalCodexExe $localCodexExe `
        -PidPath $applyPatchRewriterPid `
        -LogPath $applyPatchRewriterLog
}

# ---- Start (or restart) the bridge ----------------------------------------

Stop-ManagedBridge -PidPath $bridgePid

$resolvedProvider = $null
if ($ProviderJson) {
    if ([System.IO.Path]::IsPathRooted($ProviderJson)) {
        $resolvedProvider = $ProviderJson
    } else {
        # Resolve relative paths against the script root (where the launcher
        # lives), not the cwd, so that double-clicking the .bat from any
        # directory still finds the provider config.
        $resolvedProvider = Join-Path $scriptRoot $ProviderJson
    }
}

# CODEX_HOME is the only Codex env override we set. We deliberately do
# NOT touch USERPROFILE / APPDATA / HOME / LOCALAPPDATA / TEMP / TMP --
# those keep pointing at the user's real profile so apply_patch, MCP,
# git, rg, file dialogs, ~/.gitconfig, ~/.ssh continue to work.
#
# CODEX_HOME is set at PROCESS scope here so the bridge child process
# inherits it. AppX activation is brokered by Windows and does not
# inherit arbitrary process-scope variables from this launcher; the Codex
# GUI launch below handles that with a short-lived user-scope override.
$bridgeEnv = @{
    CODEX_HOME              = $isolatedHome
    CODEX_BRIDGE_HOST       = '127.0.0.1'
    CODEX_BRIDGE_PORT       = "$port"
    BRIDGE_LOG_PATH         = $bridgeLog
}
if ($resolvedProvider -and (Test-Path -LiteralPath $resolvedProvider)) {
    $bridgeEnv['OMNIROUTE_PROVIDER_JSON'] = $resolvedProvider
}

# Apply env vars at process scope for the bridge. The non-CODEX_HOME
# bridge variables (BRIDGE_LOG_PATH, etc.) are also kept since they do
# not affect Codex Desktop.
foreach ($kv in $bridgeEnv.GetEnumerator()) {
    [System.Environment]::SetEnvironmentVariable($kv.Key, [string]$kv.Value, 'Process')
}

"[$(Get-Date -Format o)] bridge starting node=$nodeExe port=$port codex_home=$isolatedHome" |
    Out-File -LiteralPath $bridgeLog -Encoding UTF8 -Append

$proc = $null
# -WindowStyle is Windows-only; only pass it where supported so the
# launcher also works under pwsh on Linux/macOS in CI/verification.
$startArgs = @{
    FilePath         = $nodeExe
    ArgumentList     = @($bridgeScript)
    WorkingDirectory = $scriptRoot
    PassThru         = $true
}
if (Test-WindowsHost) {
    $startArgs['WindowStyle'] = 'Hidden'
}
$proc = Start-Process @startArgs

if (-not $proc) {
    throw "[omniroute] failed to start bridge process (Start-Process returned null)"
}
try { $proc.PriorityClass = [System.Diagnostics.ProcessPriorityClass]::BelowNormal } catch {}
Set-Content -LiteralPath $bridgePid -Value $proc.Id -Encoding ASCII

try {
    $health = Wait-ForBridgeHealth -BridgeHost '127.0.0.1' -Port $port -TimeoutSec 25
    $omniSource = if ($health -and $health.omniroute) { $health.omniroute.source } else { '<unknown>' }
    Write-Host "[omniroute] bridge healthy on 127.0.0.1:$port (pid=$($proc.Id), source=$omniSource)"
} catch {
    Write-Error "[omniroute] bridge failed to come up: $($_.Exception.Message). See $bridgeLog."
    try { Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue } catch {}
    throw
}

if ($NoCodex) {
    Write-Host "[omniroute] -NoCodex: bridge is running, isolated CODEX_HOME is seeded. Codex GUI not launched."
    exit 0
}

# ---- Launch Codex via AppX broker ----------------------------------------
#
# Activating through IApplicationActivationManager gives Codex.exe its
# Microsoft Store package identity, which propagates to every child
# process Codex spawns (agent shell, apply_patch.bat -> codex.exe,
# codex-command-runner, rg, etc.). This is the same launch path
# Start Menu uses.
#
# Before activation, CODEX_HOME is written to the user's Windows
# environment. The AppX broker and late Desktop helpers build packaged
# process environments from user/machine environment state, not from this
# PowerShell process's private environment block. A hidden watcher keeps
# the user-scope override leased until the activated Desktop/AppX process
# tree exits, then restores the previous user values.

$argumentString = ''
if ($OpenProject) {
    $argumentString = "--open-project `"$OpenProject`""
}

$previousUserCodexHome = $null
$previousUserPath = $null
$expectedUserPath = $null
$setUserCodexHomeForAppx = $false
$setUserPathForAppx = $false
$activationStartedAtUtc = (Get-Date).ToUniversalTime()
if (Test-WindowsHost) {
    $previousUserCodexHome = [System.Environment]::GetEnvironmentVariable('CODEX_HOME', 'User')
    if (Test-SameEnvironmentValue $previousUserCodexHome $isolatedHome) {
        # Treat an already-present value that points at our isolated home as
        # stale state from an interrupted prior launch. We can reuse it for
        # this activation, but we still clear it in the finally block below.
        $previousUserCodexHome = $null
        $setUserCodexHomeForAppx = $true
        Write-Host "[omniroute] found stale user-scope CODEX_HOME; will clear it after AppX activation"
    } else {
        Set-UserCodexHomeOverride -Value $isolatedHome
        $setUserCodexHomeForAppx = $true
        Write-Host "[omniroute] temporarily set user-scope CODEX_HOME for AppX activation"
    }

    if ($taskkillShimDir -and (Test-Path -LiteralPath (Join-Path $taskkillShimDir 'taskkill.exe'))) {
        $previousUserPath = [System.Environment]::GetEnvironmentVariable('PATH', 'User')
        $expectedUserPath = Join-PathPrefix -PathValue $previousUserPath -Prefix $taskkillShimDir
        if (-not [string]::Equals($previousUserPath, $expectedUserPath, [System.StringComparison]::OrdinalIgnoreCase)) {
            Set-UserPathOverride -Value $expectedUserPath
            $setUserPathForAppx = $true
            Write-Host "[omniroute] temporarily prepended taskkill quiet shim to user-scope PATH for AppX activation"
        }
    } else {
        Write-Warning "[omniroute] taskkill quiet shim is unavailable; MCP app-server stdio may still be polluted by taskkill output."
    }
}

$activatedPid = 0
$activationSucceeded = $false
try {
    $activatedPid = Start-CodexViaAppx -AumId $appx.AumId -Arguments $argumentString
    $activationSucceeded = $true
} finally {
    if ($setUserCodexHomeForAppx -or $setUserPathForAppx) {
        if ($activationSucceeded) {
            $watcherStarted = Start-UserCodexHomeRestoreWatcher `
                -IsolatedHome $isolatedHome `
                -PreviousUserCodexHome $previousUserCodexHome `
                -TaskkillShimDir $(if ($setUserPathForAppx) { $taskkillShimDir } else { $null }) `
                -PreviousUserPath $previousUserPath `
                -ExpectedUserPath $expectedUserPath `
                -TimeoutSec $UserCodexHomeRestoreTimeoutSec `
                -ActivationStartedAtUtc $activationStartedAtUtc `
                -ActivatedPid $activatedPid `
                -PackageInstallLocation $appx.InstallLoc
            if (-not $watcherStarted) {
                Restore-UserCodexHomeOverrideNow `
                    -IsolatedHome $isolatedHome `
                    -PreviousUserCodexHome $previousUserCodexHome `
                    -TaskkillShimDir $(if ($setUserPathForAppx) { $taskkillShimDir } else { $null }) `
                    -PreviousUserPath $previousUserPath `
                    -ExpectedUserPath $expectedUserPath
            } else {
                Write-Host "[omniroute] user-scope CODEX_HOME/PATH overrides will be restored after Codex Desktop and its AppX helpers exit"
            }
        } else {
            Restore-UserCodexHomeOverrideNow `
                -IsolatedHome $isolatedHome `
                -PreviousUserCodexHome $previousUserCodexHome `
                -TaskkillShimDir $(if ($setUserPathForAppx) { $taskkillShimDir } else { $null }) `
                -PreviousUserPath $previousUserPath `
                -ExpectedUserPath $expectedUserPath
        }
    }
}
if ($activatedPid -gt 0) {
    Write-Host "[omniroute] launched Codex via AppX activation (pid=$activatedPid)"
} else {
    Write-Host "[omniroute] Codex AppX activation succeeded (pid not reported)"
}

Write-Host "[omniroute] tail the bridge log to watch routing:"
Write-Host "  Get-Content '$bridgeLog' -Tail 50 -Wait"
